name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main

env:
  RUST_LOG: DEBUG
  CONFIG_PATH: ${{ github.workspace }}/config.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install Tailwind
        run: |
          npm install -g tailwindcss

      - name: Build
        working-directory: ./ssg
        run: cargo build --release

      - name: Run the binary
        run: ./ssg/target/release/ssg

      - name: Cache build folder
        uses: actions/cache@v4
        with: 
          path: ./build
          key: build-cache-${{ runner.os }}-${{ hashFiles('./ssg/src/**', './ssg/Cargo.toml') }}
          restore-keys: |
            build-cache-${{ runner.os }}-
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

